name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            poetry.lock
          key: poetry-deps-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-deps-

      - name: Install dependencies
        run: |
          poetry install --with linters --no-root

      - name: Run Black
        run: |
          poetry run black src --check

      - name: Run Ruff
        run: |
          poetry run ruff check src
